dnb:
  hco:
    raw:
      resources:
        - id: "dnb_hco_1"
          source:
            api: null
            file: null
            athena:
              database: test
              table: ebx_hierarchy_hierarchy_dunAndBradstreetAccounts1
              type: athena
              query: |
                SELECT * FROM ebx_hierarchy_hierarchy_dunAndBradstreetAccounts1
                WHERE hierarchyType = 'DUNS'
          target:
            api: null
            athena: null
            file:
              bucket: adl-base-customer-mdm-etl-dev-226aog
              prefix: /raw/FS_DNB1/
              type: s3
              format: parquet
              file_name: null
        - id: "dnb_hco_2"
          source:
            api: null
            file: null
            athena:
              database: test
              table: ebx_hierarchy_hierarchy_dunAndBradstreetAccounts2
              type: athena
              query: |
                SELECT * FROM ebx_hierarchy_hierarchy_dunAndBradstreetAccounts2
                WHERE hierarchyType = 'DUNS'
          target:
            api: null
            athena: null
            file:
              bucket: adl-base-customer-mdm-etl-dev-226aog
              prefix: /raw/FS_DNB2/
              type: s3
              format: parquet
              file_name: null
    trusted: null
    enriched: null
  hcp:
    raw: null
    trusted: null
    enriched: null
sap:
  hcp:
    raw:
      resources:
        - id: "sap_hcp_1"
          source:
            api:
              s3_prefix: enriched/FS_SAP_DC_CUST/API_TESTING/
    trusted: null
    enriched: null
  hco:
    raw: null
    trusted: null
    enriched: null
sfdc:
  hcp:
    raw: null
    trusted: null
    enriched: null
  hco:
    raw: null
    trusted: null
    enriched: null