sap:
  hco:
    raw:
      source:
        athena:
          database: adl_enriched_gbl_cf_ebx
          table: ebx_hierarchy_hierarchy_dunAndBradstreetAccounts
          type: athena
      target:
        s3:
          bucket: adl-base-customer-mdm-etl-dev-226aog
          file_name: null
          prefix: /raw/FS_DNB/
          type: file
